package-lock.json
packages/lambda-powertools-middleware-correlation-ids/package-lock.json
packages/lambda-powertools-middleware-correlation-ids/package.json
packages/lambda-powertools-middleware-obfuscater/package-lock.json
packages/lambda-powertools-middleware-obfuscater/package.json

Updated dependency on lodash to latest version (4.17.11) as it 4.17.10 has security alerts.

refactor(security): update lodash after security alert

---

packages/lambda-powertools-middleware-log-timeout/README.md
packages/lambda-powertools-middleware-log-timeout/__tests__/index.js
packages/lambda-powertools-middleware-log-timeout/index.js
packages/lambda-powertools-middleware-log-timeout/package-lock.json
packages/lambda-powertools-middleware-log-timeout/package.json
packages/lambda-powertools-pattern-basic/README.md
packages/lambda-powertools-pattern-basic/index.js
packages/lambda-powertools-pattern-basic/package.json
packages/lambda-powertools-pattern-obfuscate/README.md
packages/lambda-powertools-pattern-obfuscate/index.js
packages/lambda-powertools-pattern-obfuscate/package.json

Added a middleware to log a timeout message just before an invocation is abruptly timed out by Lambda.
Using the same approach outlined in this [post](https://theburningmonk.com/2019/05/how-to-log-timed-out-lambda-invocations/)
Apply the middleware to a function that'll definitely time out, e.g.
```javascript
const middy = require('middy')
const logTimeout = require('@perform/lambda-powertools-middleware-log-timeout')
const handler = (event, context, cb) => {
// oops, forgot to call callback!
}
module.exports = middy(handler)
.use(logTimeout())
}
```

feat: add log-timeout middleware

---

package.json
packages/lambda-powertools-correlation-ids/package.json
packages/lambda-powertools-http-client/package.json
packages/lambda-powertools-kinesis-client/package.json
packages/lambda-powertools-lambda-client/package.json
packages/lambda-powertools-logger/package.json
packages/lambda-powertools-middleware-correlation-ids/package.json
packages/lambda-powertools-middleware-obfuscater/package.json
packages/lambda-powertools-middleware-sample-logging/package.json
packages/lambda-powertools-pattern-basic/package.json
packages/lambda-powertools-pattern-obfuscate/package.json
packages/lambda-powertools-sns-client/package.json
packages/lambda-powertools-sqs-client/package.json
packages/lambda-powertools-step-functions-client/package.json

Added MIT license to all packages as currently none of them have a license, e.g.

chore: added MIT license info to all repos

---

.drone.yml

Node v10.16 was recently released with npm@6.9.0 bundled with it.
npm@6.9.0 has a [serious issue breaking our CI pipeline](https://github.com/npm/cli/pull/173#issuecomment-498020090), so let's avoid it by downgrading to Node v10.15 which is bundled with npm@6.4.1
Downgrading Node (and therefore npm) to the last working version. Should be a temporary measure until npm@6.9.1 is released.
Drone pipeline is now passing again.

ci(drone): force setup with node v10.15

---

README.md
packages/lambda-powertools-middleware-correlation-ids/__tests__/index.js
packages/lambda-powertools-middleware-correlation-ids/index.js
packages/lambda-powertools-middleware-stop-infinite-loop/README.md
packages/lambda-powertools-middleware-stop-infinite-loop/__tests__/index.js
packages/lambda-powertools-middleware-stop-infinite-loop/index.js
packages/lambda-powertools-middleware-stop-infinite-loop/package-lock.json
packages/lambda-powertools-middleware-stop-infinite-loop/package.json

Closes #38 
Tracks the length of a call chain and stop infinite loops.
* Updated the `correlation-ids` middleware so that it initializes a `call-chain-length`and includes it as part of the correlation IDs (which would be forwarded by other client libs).
* Added a new `stop-infinite-loop` middleware, which inspects the `call-chain-length` correlation ID and throws (before invocating the user code) if it has reached the configured threshold.
* set up a function which recurses indefinitely
* apply this middleware
* see that after X recursions, the function is stopped

feat: track call-chain length and stop infinite loops

---

README.md

The line that says that you still have `that one decision to start debugging` is a little confusing, and the text in parenthesis does not clarify things up. Here is a re-wording of the text with what I understood was the intended effect.
But I'm not 100% sure =P.

docs: README text `that one decision to start debugging` is confusing

---

packages/lambda-powertools-pattern-basic/__tests__/index.js
packages/lambda-powertools-pattern-basic/__tests__/supplement-csv.js
packages/lambda-powertools-pattern-basic/index.js
packages/lambda-powertools-pattern-basic/supplement-csv.js

Closes #41 
Doesn't overwrite `process.env.DATADOG_TAGS`
Only assigns `process.env.DATADOG_TAGS` if they have not been assigned
This is a very trivial bug fix and so hopefully this is out of scope.
***Is this ready for review?:*** Yes

fix: fixes datadog tags overwritten

---

packages/lambda-powertools-logger/README.md
packages/lambda-powertools-logger/__tests__/index.js
packages/lambda-powertools-logger/index.js

This change is to have the option to log the error details without having to pass the `params` argument when invoking `Logger#warn` or `Logger#error`. It reflects more the `console#error` way which most of developers are used to.
In `Logger#warn` and `Logger#error` functions in case  `err` is not defined and `params` is an instance of `Error`, then the error details will be included in the logging.
Examples:
```javascript
Log.warn('this is a warning message', new Error('oops'))
// or
Log.error('this is an error message', new Error('oops'))
```
Changes are backward compatible.
Both these statements return the same output structure:
```
Log.error('this is an error message', {}, new Error('oops'))
Log.error('this is an error message', new Error('oops'))
```
***Is this ready for review?:*** …

feat(logger): make params optional when logging the error stack

---

packages/lambda-powertools-middleware-log-timeout/__tests__/index.js
packages/lambda-powertools-middleware-log-timeout/index.js
packages/lambda-powertools-middleware-log-timeout/package-lock.json

Closes #82 #86
Check the timer is set before attempting to run `clearTimer`.

fix(log-timeout): check timer is set before attempting to clear

---

packages/lambda-powertools-firehose-client/package-lock.json
packages/lambda-powertools-middleware-correlation-ids/__tests__/api-gateway.js
packages/lambda-powertools-middleware-correlation-ids/event-sources/api-gateway.js

Closes #92 
* for the API Gateway event source, use the `event.requestContext.requestId` (which is the API Gateway request ID) to initialize as our correlation ID

use API Gateway's requestId to initialize correlation Id

---

packages/lambda-powertools-pattern-obfuscate/__tests__/index.js
packages/lambda-powertools-pattern-obfuscate/__tests__/supplement-csv.js
packages/lambda-powertools-pattern-obfuscate/index.js
packages/lambda-powertools-pattern-obfuscate/supplement-csv.js

For now this duplicates supplement-csv module from pattern-basic. In the
(hopefully) near future this module should be published on its own
package.
Prevent overriding existing `DATADOG_TAGS` values.
Closes #103
Following same approach as in pattern-basic, using supplement-csv function
helper to update the `DATADOG_TAGS` while keeping original values.
A new test has been added that reproduces and ensures the `DATADOG_TAGS` values
are respected.

fix(pattern-obfuscate): keep original DATADOG_TAGS values

---

layer/build.sh

Update shebang to use `sh` instead of `bash`
https://circleci.com/docs/2.0/using-shell-scripts/

ci: update script shebang

---

packages/lambda-powertools-pattern-basic/__tests__/index.js
packages/lambda-powertools-pattern-basic/index.js
packages/lambda-powertools-pattern-obfuscate/__tests__/index.js
packages/lambda-powertools-pattern-obfuscate/index.js

Changed the behavior that overrides `DATADOG_PREFIX` if it is undefined or
empty.
Override only if it is `undefined`.
The tests illustrate the new behavior.
***Is it a breaking change?:*** YES

Override DATADOG_PREFIX only if it is not defined

---

packages/lambda-powertools-middleware-sample-logging/__tests__/index.js
packages/lambda-powertools-middleware-sample-logging/index.js

Closes #133
The sample logging middleware's `onError` handler tolerates when `context` is omitted, which is often the case in test code.

feat: handle cases when context is undefined

---

packages/lambda-powertools-http-client/__tests__/metrics.js
packages/lambda-powertools-http-client/index.js

Closes #138
Noticed that the `metricName` option was being ignored and found a typo when pulling trying to pull the metricName from the options [here](https://github.com/getndazn/dazn-lambda-powertools/blob/master/packages/lambda-powertools-http-client/index.js#L100) which causes the url.hostname to always be used instead. Wrote tests to verify the same behavior we've been seeing in our implementation and then fixed the typo to make those tests go green.
I've already wrote tests to verify this in the metrics.js, but can be easily verified by passing in the `metricName` option when using the http-client and verify that the prefix actually gets used in the outputted histogram and count metrics that are generated from the response.
***Is it a breaking …

fix(http-client): honor custom metricName option when passed in

---

packages/lambda-powertools-http-client/README.md
packages/lambda-powertools-http-client/__tests__/request.js
packages/lambda-powertools-http-client/index.js

Closes #140 and #141
Modified http client to support PATCH method and pass through properly to superagent since it currently already supports PATCH.
Modified http client options to allow `url` to be used as an option if `uri` isn't present to assist in migration and adoption from other clients.
I can split this into multiple PRs if desired, but both of these features were 2 of biggest issues we kept running into when switching our services over to use the dazn http client, so I addressed them together since both changes were quite small.
I wrote tests for both of these in the request.js file to make sure that all http methods get called as expected and both the uri/url options are being used properly.

feat(http-client): add support for patch and url option

---

packages/lambda-powertools-middleware-sample-logging/index.js

I allowed users to have the choice if their uncaught errors are to be logged. This allows people to send validation errors to appsync or step functions without being logged out as errors.
https://github.com/getndazn/dazn-lambda-powertools/issues/145
I added an enviroment variable ( POWERTOOLS_IGNORE_ERRORS ) following a proposed standard from https://github.com/getndazn/dazn-lambda-powertools/issues/53. to give people the choice if they want there uncaught errors to be logged.
Have a lambda function return an error wrapped with sample logging middleware. Ensure that when enviroment variable POWERTOOLS_IGNORE_ERRORS  = true then it doesn't log errors sent back. Also when POWERTOOLS_IGNORE_ERRORS is anything else that it logs the errors.
***Is this ready for review?:*** Yes
***Is it a …

feat(sample logging middleware)

---

packages/lambda-powertools-cloudwatchevents-client/package-lock.json
packages/lambda-powertools-eventbridge-client/package-lock.json
packages/lambda-powertools-lambda-client/index.js
packages/lambda-powertools-middleware-correlation-ids/package.json

Closes #149 
The AWS SDK dependency is now a dev dependency only for the correlation IDs middleware to avoid bloating.

feat: made aws-sdk dev dep in correlation ids pkg

---

.circleci/config.yml

The docs on master are failing as the [CI tries to delete the `gh-pages` branch](https://circleci.com/gh/getndazn/dazn-lambda-powertools/1118) but cannot since it doesn't exist. This PR makes the step optional to prevent the build from failing. 
As above. 
Merge to master! 

build: make deleting docs branch optional

---

package.json

Builds are currently failing due to the package-locks being bumped for minor versions

ci(lerna): force npm ci

---

example/package-lock.json
packages/lambda-powertools-cloudwatchevents-client/package-lock.json
packages/lambda-powertools-dynamodb-client/package-lock.json
packages/lambda-powertools-dynamodb-client/package.json
packages/lambda-powertools-eventbridge-client/package-lock.json
packages/lambda-powertools-eventbridge-client/package.json
packages/lambda-powertools-firehose-client/package-lock.json
packages/lambda-powertools-firehose-client/package.json
packages/lambda-powertools-http-client/package-lock.json
packages/lambda-powertools-kinesis-client/package-lock.json
packages/lambda-powertools-kinesis-client/package.json
packages/lambda-powertools-lambda-client/package-lock.json
packages/lambda-powertools-lambda-client/package.json
packages/lambda-powertools-middleware-correlation-ids/package-lock.json
packages/lambda-powertools-middleware-log-timeout/package-lock.json
packages/lambda-powertools-middleware-obfuscater/package-lock.json
packages/lambda-powertools-middleware-sample-logging/package-lock.json
packages/lambda-powertools-middleware-stop-infinite-loop/package-lock.json
packages/lambda-powertools-pattern-basic/package-lock.json
packages/lambda-powertools-pattern-obfuscate/package-lock.json
packages/lambda-powertools-sns-client/package-lock.json
packages/lambda-powertools-sns-client/package.json
packages/lambda-powertools-sqs-client/package-lock.json
packages/lambda-powertools-sqs-client/package.json
packages/lambda-powertools-step-functions-client/package-lock.json
packages/lambda-powertools-step-functions-client/package.json

Since aws-sdk is included in the lambda runtime, often users want to exclude it from their function
packages. When aws-sdk is imported as a direct dependency then users have to manually remove it from their node_modules directory.
I've switched aws-sdk to a dev dep so it becomes the user's choice whether they want to fix the aws-sdk version and include it in their bundle or not.
Install one of the packages, observe that aws-sdk is no longer in your node_modules dir.

fix(deps): aws-sdk should not be a direct dependency

---

package.json

* Skip CI when tagged releases are pushed by lerna as no changes are made to publish but build still fails due to updated package lock files.

ci(circleci): skip ci when running new lerna version

---

example/package-lock.json
package-lock.json
package.json
packages/lambda-powertools-cloudwatchevents-client/package-lock.json
packages/lambda-powertools-dynamodb-client/package-lock.json
packages/lambda-powertools-eventbridge-client/package-lock.json
packages/lambda-powertools-firehose-client/package-lock.json
packages/lambda-powertools-http-client/package-lock.json
packages/lambda-powertools-kinesis-client/package-lock.json
packages/lambda-powertools-lambda-client/package-lock.json
packages/lambda-powertools-middleware-correlation-ids/package-lock.json
packages/lambda-powertools-middleware-log-timeout/package-lock.json
packages/lambda-powertools-middleware-obfuscater/package-lock.json
packages/lambda-powertools-middleware-sample-logging/package-lock.json
packages/lambda-powertools-middleware-stop-infinite-loop/package-lock.json
packages/lambda-powertools-pattern-basic/package-lock.json
packages/lambda-powertools-pattern-obfuscate/package-lock.json
packages/lambda-powertools-sns-client/package-lock.json
packages/lambda-powertools-sqs-client/package-lock.json
packages/lambda-powertools-step-functions-client/package-lock.json

* Update lerna to `3.20.2` so when a lerna creates a new version tagged release, it ensures that all relevant package-lock files are also updated - https://github.com/lerna/lerna/releases/tag/v3.18.2

chore: update lerna

---

package.json

* Remove deprecated version arg when performing `lerna version` - `WARN deprecated --github-release has been replaced by --create-release=github`

chore: update lerna version command

---

.circleci/config.yml
example/package-lock.json
layer/nodejs/package-lock.json
package-lock.json
package.json
packages/lambda-powertools-cloudwatchevents-client/package-lock.json
packages/lambda-powertools-dynamodb-client/package-lock.json
packages/lambda-powertools-eventbridge-client/package-lock.json
packages/lambda-powertools-firehose-client/package-lock.json
packages/lambda-powertools-http-client/package-lock.json
packages/lambda-powertools-kinesis-client/package-lock.json
packages/lambda-powertools-lambda-client/package-lock.json
packages/lambda-powertools-logger/package-lock.json
packages/lambda-powertools-middleware-correlation-ids/package-lock.json
packages/lambda-powertools-middleware-log-timeout/package-lock.json
packages/lambda-powertools-middleware-obfuscater/package-lock.json
packages/lambda-powertools-middleware-sample-logging/package-lock.json
packages/lambda-powertools-middleware-stop-infinite-loop/package-lock.json
packages/lambda-powertools-pattern-basic/package-lock.json
packages/lambda-powertools-pattern-obfuscate/package-lock.json
packages/lambda-powertools-sns-client/package-lock.json
packages/lambda-powertools-sqs-client/package-lock.json
packages/lambda-powertools-step-functions-client/package-lock.json

When running `lerna bootstrap` all dependencies should be installed in packages. However, due to a bug listed: https://github.com/lerna/lerna/issues/1457, this doesn't currently happen. Due to this, package-lock files for all packages are not fully representative of all deps and dev deps.
As a workaround, update from using `lerna bootstrap` to performing the commands as 2 commands manually.
This will allow package-lock files to be in sync as well as allowing dependabot automated updates to not fail.
All package-lock files have also been updated as a result.
Update the `install` npm script to run `lerna exec npm ci && lerna link`
Run `npm i` and ensure all packages have dependencies install and symlinked with package-lock files also updated with all dependencies.
***Is this ready for …

build(deps): install all deps

---

.circleci/config.yml
package.json

Use `npm i` instead of `npm ci` during bootstrapping so that package-lock files can be in sync with previously published powertools packages. This is because, lerna does not update the dependency versions in lock files during `lerna version` and future builds fail as lock files are out of sync when doing `npm ci` on future builds.
Use `npm i` instead of `lerna exec npm ci`.
The build in this PR passes (since master has received a released version bump recently).

ci(circleci): update install script

---

packages/lambda-powertools-middleware-correlation-ids/README.md

Just a really quick fix to a typo as on the below page:
https://github.com/getndazn/dazn-lambda-powertools/tree/master/packages/lambda-powertools-middleware-correlation-ids
Review the readme

docs(readme): typo

---

packages/lambda-powertools-correlation-ids/README.md
packages/lambda-powertools-correlation-ids/__tests__/index.js
packages/lambda-powertools-correlation-ids/index.js

Closes #237
CorrelationIds already had a convenience method for checking to see if `debug-log-enabled` was set, but no accompanying convenience method for setting said flag. In fact, the existing method looked to be unused and untested!
I've renamed the getter to be more meaningful (`debugEnabled` -> `debugLoggingEnabled`), added an associated setter, and added a test to show usage. In addition, I've updated the readme to show example usage.
Run tests!

feat: added support for setting debug logging within CorrelationIds
