getndazn/dazn-lambda-powertools

packages/lambda-powertools-correlation-ids/package.json, packages/lambda-powertools-http-client/package.json, packages/lambda-powertools-kinesis-client/package.json, packages/lambda-powertools-lambda-client/package.json, packages/lambda-powertools-logger/package.json, packages/lambda-powertools-middleware-correlation-ids/package.json, packages/lambda-powertools-middleware-obfuscater/package.json, packages/lambda-powertools-middleware-sample-logging/package.json, packages/lambda-powertools-pattern-basic/package.json, packages/lambda-powertools-pattern-obfuscate/package.json, packages/lambda-powertools-sns-client/package.json, packages/lambda-powertools-sqs-client/package.json, packages/lambda-powertools-step-functions-client/package.json
Make the NPM packages public as part of the drive to open source the project.
**Is it a breaking change?:*** NO
=> build: make our packages public

README.md
Fixed lerna broken link.
Updated readme with the correct lerna homepage link.
Click on the readme's lerna homepage link.
=> docs: Fix lerna homepage link

.drone.yml, packages/lambda-powertools-http-client/__tests__/metrics.js
- Fixes deployments by stopping setup from modifying the `package-lock`
- Run tests against Node 8, 10 and 12
- Update the Drone pipeline to use Node 10 (npm@6) so we can use `npm ci`
- Add parallel steps to Drone for testing Node 8, 10 and 12
- The Drone pipeline will pass on pushes to master
N/A - CI changes only
=> Test on multiple node versions + use npm ci

packages/lambda-powertools-middleware-log-timeout/__tests__/index.js, packages/lambda-powertools-middleware-log-timeout/index.js
=> fix: handle missing getRemainingTimeInMillis gracefully

packages/lambda-powertools-sns-client/README.md, packages/lambda-powertools-sns-client/__tests__/index.js, packages/lambda-powertools-sns-client/index.js, packages/lambda-powertools-sqs-client/README.md, packages/lambda-powertools-sqs-client/__tests__/index.js, packages/lambda-powertools-sqs-client/index.js
=> fix: stringify call-chain-length for SNS and SQS param

packages/lambda-powertools-http-client/__tests__/correlation-ids.js, packages/lambda-powertools-http-client/__tests__/metrics.js, packages/lambda-powertools-http-client/index.js
=> fix: don't set null/undefined HTTP headers

packages/lambda-powertools-http-client/README.md, packages/lambda-powertools-http-client/__tests__/timeout.js, packages/lambda-powertools-http-client/index.js
=> feat(http_client): add support for timeout

packages/lambda-powertools-http-client/__tests__/correlation-ids.js, packages/lambda-powertools-http-client/index.js
=> fix: fixed overly aggressive null/undefined check

packages/lambda-powertools-kinesis-client/index.js, packages/lambda-powertools-lambda-client/index.js, packages/lambda-powertools-sns-client/index.js, packages/lambda-powertools-sqs-client/index.js, packages/lambda-powertools-step-functions-client/index.js
=> feat: enable HTTP keep alive on AWS clients

packages/lambda-powertools-logger/index.js
feat(logger): add static level getter.  This allows us to log different levels of detail depending on the level.  Currently only possible when creating an instance.
Allows level to be checked when using the global logger
static getter following existing static pattern
one liner
=> feat(logger): add static level getter

.circleci/config.yml
Closes #XXXXX
***Is this ready for review?:*** NO
=> ci(git): persist ssh on new version step

.circleci/config.yml
Closes #XXXXX
***Is this ready for review?:*** NO
=> ci(publish): fix publish step

.circleci/config.yml, packages/lambda-powertools-http-client/README.md, packages/lambda-powertools-http-client/__tests__/metrics.js, packages/lambda-powertools-http-client/index.js, packages/lambda-powertools-http-client/package-lock.json, packages/lambda-powertools-http-client/package.json
Closes #51 
Use the new public package for datadog metrics.
=> fix(http-client): update metrics package

.circleci/config.yml
Fixes git config for Lerna new version
=> fix: publishing package step update

layer/build.sh
CI script hotfix for publishing SAR app
=> fix: add missing shebang to layer script

.circleci/config.yml
=> ci: update step command for sar app

.circleci/config.yml
Update executor image and include sam cli.
=> ci: update SAR app steps

.circleci/config.yml
Update steps to allow for successful publishing of the SAR app.
=> ci: update SAR app publish steps

example/serverless.yml
Updated the node version since nodejs8.10 is no longer supported for creating or updating AWS Lambda functions.
Updated the serverless.yml.
Deploy the example.
=> Updated nodejs vesion to 12.x

packages/lambda-powertools-lambda-client/index.js
Closes #XXXXX
Adds support for local executions using the default values of serverless-offline-plugin.
Checking for a well-known environment variable that indicates local execution.
Create a project with serverless framework and use the serverless-offline-plugin for local execution.
=> Added support for offline development

.circleci/config.yml, .gitignore, SUMMARY.md, book.json, package-lock.json, package.json
Closes #132 and adds hosted docs. Grabs all of the packages README's and bundles them into hosted documentation. We can then switch on github pages for that branch be deployed on: `getndazn.github.io/dazn-lambda-powertools` we can then add a custom domain after if we wish. 
The docs run on master merge and push to the `gh-pages` branch. Whilst this isn't strictly necessary it seems better than committing into the repo, or creating our own infrastructure (for now). The pattern for pushing the `_book` folder is [based on this document](https://gist.github.com/cobyism/4730490). I'm open to ideas if there are easier ways to do it. 
Note: [This comment](https://gist.github.com/cobyism/4730490#user-content-step-2) does seem to suggest that the `_book` directory must already be known to git in …
=> Added Hosted Docs

README.md
Minor one as I realised we had no install step on the home page.
N/A
N/A
- [] Provide verification config / projects / resources
- [] Enable "Allow edits from maintainers" for this PR
=> Add NPM install step to the README

.circleci/config.yml
Fix for previous PR: https://github.com/getndazn/dazn-lambda-powertools/pull/153
Error reference: https://circleci.com/gh/getndazn/dazn-lambda-powertools/1048
```
npm ERR! path /home/circleci/project/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/circleci/project/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
```
Persist workspace on the docs step of the build. 
Unsure, apart from merging to master (but the impact is small as it should only affect the docs step). 
=> chore: Fix CI by persisting workspace on docs step for CircleCI

.circleci/config.yml
Currently the docs are failing given the current method. It was a little trickier than I expected to get it into CI. I'm sure there's a workable fix but for now I'm temporarily removing the docs so we can get the build back to green and merge the other features. We can use the same commands to build manually where needed until I get a chance to address the failure and re-add to the CI. 
Removal from CircleCI config
Merge to master, ensure that build passes
=> Temporarily remove docs to prevent CI failure

package.json
Reverts getndazn/dazn-lambda-powertools#162
=> Revert "ci(lerna): force npm ci"

example/package-lock.json, packages/lambda-powertools-cloudwatchevents-client/package-lock.json, packages/lambda-powertools-dynamodb-client/package-lock.json, packages/lambda-powertools-eventbridge-client/package-lock.json, packages/lambda-powertools-firehose-client/package-lock.json, packages/lambda-powertools-http-client/package-lock.json, packages/lambda-powertools-kinesis-client/package-lock.json, packages/lambda-powertools-lambda-client/package-lock.json, packages/lambda-powertools-middleware-correlation-ids/package-lock.json, packages/lambda-powertools-middleware-log-timeout/package-lock.json, packages/lambda-powertools-middleware-obfuscater/package-lock.json, packages/lambda-powertools-middleware-sample-logging/package-lock.json, packages/lambda-powertools-middleware-stop-infinite-loop/package-lock.json, packages/lambda-powertools-pattern-basic/package-lock.json, packages/lambda-powertools-pattern-obfuscate/package-lock.json, packages/lambda-powertools-sns-client/package-lock.json, packages/lambda-powertools-sqs-client/package-lock.json, packages/lambda-powertools-step-functions-client/package-lock.json
* All package-locks are out of sync which is why the builds are breaking as lerna sees the git diffs
=> fix: update package-locks

packages/lambda-powertools-middleware-correlation-ids/package-lock.json, packages/lambda-powertools-middleware-correlation-ids/package.json
Reverts getndazn/dazn-lambda-powertools#179
=> Revert "build(deps-dev): [security] bump lodash from 4.17.11 to 4.17.13"

.circleci/config.yml, package.json
Reverts getndazn/dazn-lambda-powertools#200
=> Revert "ci(circleci): update install script"

example/package-lock.json, layer/nodejs/package-lock.json, packages/lambda-powertools-cloudwatchevents-client/package-lock.json, packages/lambda-powertools-dynamodb-client/package-lock.json, packages/lambda-powertools-eventbridge-client/package-lock.json, packages/lambda-powertools-firehose-client/package-lock.json, packages/lambda-powertools-http-client/package-lock.json, packages/lambda-powertools-kinesis-client/package-lock.json, packages/lambda-powertools-lambda-client/package-lock.json, packages/lambda-powertools-middleware-correlation-ids/package-lock.json, packages/lambda-powertools-middleware-log-timeout/package-lock.json, packages/lambda-powertools-middleware-obfuscater/package-lock.json, packages/lambda-powertools-middleware-sample-logging/package-lock.json, packages/lambda-powertools-middleware-stop-infinite-loop/package-lock.json, packages/lambda-powertools-pattern-basic/package-lock.json, packages/lambda-powertools-pattern-obfuscate/package-lock.json, packages/lambda-powertools-sns-client/package-lock.json, packages/lambda-powertools-sqs-client/package-lock.json, packages/lambda-powertools-step-functions-client/package-lock.json
* Package locks are currently out of sync due to dependabot enablement. This PR updates the lock files to be in sync with package.json again. 
* Dependabot will currently be disabled whilst we find a solution to enable it again.
=> chore: update lock files

.circleci/config.yml, package.json
Fix strange behaviour with Lerna and package-lock files by moving back to lerna bootstrap
Remove explicit lerna install steps and use the "basic" lerna bootstrap option
`CI=true npm ci` runs without making any modifications to lockfiles
=> Use lerna bootstrap to prevent the lockfile issues

.circleci/config.yml, README.md, jest.config.js, package-lock.json, package.json, packages/lambda-powertools-cloudwatchevents-client/package.json, packages/lambda-powertools-correlation-ids/package.json, packages/lambda-powertools-dynamodb-client/package.json, packages/lambda-powertools-eventbridge-client/package.json, packages/lambda-powertools-firehose-client/package.json, packages/lambda-powertools-http-client/__tests__/correlation-ids.js, packages/lambda-powertools-http-client/package.json, packages/lambda-powertools-kinesis-client/package.json, packages/lambda-powertools-lambda-client/package.json, packages/lambda-powertools-logger/package.json, packages/lambda-powertools-middleware-correlation-ids/package.json, packages/lambda-powertools-middleware-log-timeout/package.json, packages/lambda-powertools-middleware-obfuscater/package.json, packages/lambda-powertools-middleware-sample-logging/package.json, packages/lambda-powertools-middleware-stop-infinite-loop/package.json, packages/lambda-powertools-pattern-basic/package.json, packages/lambda-powertools-sns-client/package.json, packages/lambda-powertools-sqs-client/package.json, packages/lambda-powertools-step-functions-client/package.json
We currently test every project for every project, so we run far more tests than we need to.
Using jest projects, we can parallelise and run the test suite for each package ONCE
Run `npm t`
=> Run tests once to improve speed + usability

packages/lambda-powertools-middleware-correlation-ids/event-sources/alb.js, packages/lambda-powertools-middleware-correlation-ids/event-sources/api-gateway.js
=> feat(middleware-correlation-ids): fixing error thrown by isMatch

packages/lambda-powertools-correlation-ids/index.d.ts
Adds types missing from changes made in #238.
See new type additions in `packages/lambda-powertools-correlation-ids/index.d.ts`
=> (feat): Adds missing types to lambda-powertools-correlation-ids

packages/lambda-powertools-middleware-correlation-ids/index.d.ts, packages/lambda-powertools-pattern-basic/index.d.ts, packages/lambda-powertools-pattern-obfuscate/index.d.ts
Just updated the typings to work with middy 2
***Is it a breaking change?:*** Yes
@theburningmonk this should help with your PR
=> feat: upgrade types to reflect middy v2.x usage
